general {
    # Comando para bloquear (evita lanzar doble hyprlock si ya está abierto)
    lock_cmd = pidof hyprlock || hyprlock
    
    # Antes de entrar en suspensión (cerrar tapa), bloquea la pantalla.
    before_sleep_cmd = loginctl lock-session
    
    # Al despertar, enciende la pantalla si estaba apagada
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Opcional: Bloquear automáticamente si dejas la PC sola 5 minutos (300s)
#listener {
#    timeout = 300
#    on-timeout = loginctl lock-session
#}

# Opcional: Apagar pantalla si dejas la PC sola 5.5 minutos (330s)
#listener {
#    timeout = 330
#    on-timeout = hyprctl dispatch dpms off
#    on-resume = hyprctl dispatch dpms on
#}

# Opcional: Suspender si dejas la PC sola 1 hora (3600s)
#listener {
#    timeout = 3600
#    on-timeout = systemctl suspend
#}
