general {
    # Command used to lock (avoids launching double hyprlock if it's already open)
    lock_cmd = pidof hyprlock || hyprlock
    
    # Before sleep (close lid), lock the screen.
    before_sleep_cmd = loginctl lock-session
    
    # After waking up, turn on the screen if it was off
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Optional: Lock automatically if you left your PC inactive five minutes (300s)
#listener {
#    timeout = 300
#    on-timeout = loginctl lock-session
#}

# Optional: Turns off the screen if you left your PC inactive 5.5 minutes (330s)
#listener {
#    timeout = 330
#    on-timeout = hyprctl dispatch dpms off
#    on-resume = hyprctl dispatch dpms on
#}

# Optional: Suspend if you leave your PC alone for 1 hour (3600s)
#listener {
#    timeout = 3600
#    on-timeout = systemctl suspend
#}
