#Do not put your configuration here, just modify the paths

source = ~/.config/hypr/themes/silae/hyprland/colors/colors.conf
source = ~/.config/hypr/themes/silae/hyprland/config/monitors.conf
source = ~/.config/hypr/themes/silae/hyprland/config/programs.conf
source = ~/.config/hypr/themes/silae/hyprland/config/autostart.conf
source = ~/.config/hypr/themes/silae/hyprland/config/environment.conf
source = ~/.config/hypr/themes/silae/hyprland/config/permissions.conf
source = ~/.config/hypr/themes/silae/hyprland/config/look_and_feel.conf
source = ~/.config/hypr/themes/silae/hyprland/config/input.conf
source = ~/.config/hypr/themes/silae/hyprland/config/keybindings.conf
source = ~/.config/hypr/themes/silae/hyprland/config/window_rules.conf
