$theme = ~/.config/hypr/themes/silae/hyprlock

source = $theme/colors/colors.conf
source = $theme/config/general.conf
source = $theme/config/background.conf
source = $theme/config/top_card.conf
source = $theme/config/logo.conf
source = $theme/config/bottom_card.conf
source = $theme/config/input_field.conf
