#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

#exec-once = $terminal
exec-once = swaybg -i $wallpaper -m fill
exec-once = dunst
# exec-once = nm-applet &
exec-once = waybar #& hyprpaper & firefox
# Starts the authentication agent and the keyring
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets
exec-once = hypridle

# Starts the clipboard history (text and images)
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
