###################
### PERMISSIONS ###
###################

# See https://wiki.hypr.land/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

ecosystem {
  enforce_permissions = 1
}

permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(bin|local/bin)/slurp, screencopy, allow
#permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow #in case you installed the portal by package manager instead of building it yourself
permission = /usr/local/libexec/xdg-desktop-portal-hyprland, screencopy, allow #in case you built the portal yourself and installed it to /usr/local/libexec
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow #Only applies if you have hyprpm installed, but make sure to read the wiki page about it first, as it can be a security risk if you don't know what you're doing