##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on,match:class ^$,match:title ^$,match:xwayland 1,match:float 1,match:fullscreen 0,match:pin 0

xwayland {
  force_zero_scaling = true
}

layerrule = blur on, match:namespace wofi
layerrule = ignore_alpha 0, match:namespace wofi
# Optional: Increases the blur to the wofi menu (if you want to)
# layerrule = blurpopups, match:namespace wofi

#---- GLASS EFFECTS FOR NOTIFICATIONS ----
# Applies blut to the notifications
layerrule = blur on, match:namespace notifications

#Avoids blur seeing weird on parts totally transparents
layerrule = ignore_alpha 0, match:namespace notifications

#(Optional) If you want the notifications appear with a smooth fade animation 
layerrule = animation fade, match:namespace notifications

#Forces Terraria to float (It was for a personal bug with the game, if you want, you can comment that)
windowrule = float on, center on, size 1920 1200, match:class ^(Terraria.bin.x86_64)$

#Picture-in-Picture
windowrule {
    name = picture-in-picture

    match:title = ^([Pp]icture[- ]?[Ii]n[- ]?[Pp]icture)(.*)$
    float = true
    keep_aspect_ratio = true
    pin = true
    move = 73% 72%
    size = 25% 25%
}
