####################################
# BACKGROUND
####################################
background {
    monitor =
    path = screenshot
    color = $bg_color
    blur_passes = 3
    blur_size = 7
    noise = 0.012
    contrast = 0.90
    brightness = 0.58
    vibrancy = 0.08
    vibrancy_darkness = 0.15
}
