####################################
# BOTTOM CARD
####################################

# Bottom card shape (Optional — uncomment to enable)
#shape {
#    monitor =
#    size = 950, 180
#    color = $card
#    rounding = 24
#    border_size = 1
#    border_color = $card_border
#    position = 0, -305
#    halign = center
#    valign = center
#}

# Night / session indicator (Optional — uncomment to enable)
#label {
#    monitor =
#    text = 
#    color = $success
#    font_size = 31
#    font_family = $icons
#    position = -410, -255
#    halign = center
#    valign = center
#}

#label {
#    monitor =
#    text = Locked
#    color = $muted
#    font_size = 16
#    font_family = $font
#    position = -310, -255
#    halign = center
#    valign = center
#}

####################################
# BATTERY
####################################
image {
    monitor =
    path = $theme/assets/battery-icon.png
    size = 22
    position = 345, -255
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] $theme/scripts/battery.sh
    color = $text
    font_size = 18
    font_family = $font
    position = 400, -255
    halign = center
    valign = center
}

####################################
# KEYBOARD
####################################
image {
    monitor =
    path = $theme/assets/keyboard-icon.png
    size = 41
    rounding = 0
    border_size = 0
    position = -400, -255
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:500] $theme/scripts/keyboard.sh
    color = $muted
    font_size = 17
    font_family = $font
    position = -338, -255
    halign = center
    valign = center
}

# Empty output makes this label disappear while Caps Lock is disabled.
label {
    monitor =
    text = cmd[update:250] $theme/scripts/capslock.sh
    color = $muted
    font_size = 17
    font_family = $font
    position = 0, -255
    halign = center
    valign = center
}
