####################################
# PASSWORD FIELD
####################################
input-field {
    monitor =
    size = 890, 52
    outline_thickness = 3
    inner_color = $bg_color
    outer_color = $accent
    check_color = $input_check
    fail_color = $input_fail
    font_color = $text
    font_family = $font
    fade_on_empty = false
    rounding = 18
    placeholder_text =
    fail_text = <b>Se equivocó iiiii</b>#$PAMFAIL
    check_text =
    dots_center = true
    dots_size = 0.26
    dots_spacing = 0.32
    dots_rounding = 1
    position = 0, -330
    halign = center
    valign = center
}
