####################################
# LOGO
####################################
image {
    monitor =
    path = $theme/assets/silson.png
    size = 360
    rounding = 0
    border_size = 0
    position = 0, 45
    halign = center
    valign = center
}
