####################################
# TOP CARD
####################################

# Top card shape (Optional — uncomment to enable)
#shape {
#    monitor =
#    size = 580, 110
#    color = $card
#    rounding = 22
#    border_size = 1
#    border_color = $card_border
#    position = 0, 360
#    halign = center
#    valign = center
#}

# Avatar ring and transparent avatar asset.
shape {
    monitor =
    size = 58, 58
    color = $avatar_ring_bg
    rounding = 29
    border_size = 2
    border_color = $accent
    position = -251, 360
    halign = center
    valign = center
}

image {
    monitor =
    path = $theme/assets/avatar.png
    size = 27
    position = -251, 360
    halign = center
    valign = center
}

# Welcome label
label {
    monitor =
    text = <b>Welcome back, ae!</b>
    color = $text
    font_size = 28
    font_family = $font
    position = 5, 380
    halign = center
    valign = center
}

# Date label
label {
    monitor =
    text = cmd[update:60000] date '+%A, %B %-d'
    color = $accent
    font_size = 22
    font_family = $font
    position = 5, 335
    halign = center
    valign = center
}

# Hour label
label {
    monitor =
    text = cmd[update:60000] date '+%H'
    color = $accent
    font_size = 22
    font_family = $font
    position = 250, 375
    halign = center
    valign = center
}

# Minute label
label {
    monitor =
    text = cmd[update:60000] date '+%M'
    color = $text
    font_size = 22
    font_family = $font
    position = 250, 345
    halign = center
    valign = center
}
